# Generated by Django 2.1.3 on 2019-11-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=50, verbose_name='标题')),
                ('blog_content', models.TextField(verbose_name='内容')),
                ('blog_ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blog_utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('e_major', models.CharField(max_length=50, verbose_name='专业')),
                ('e_sdate', models.DateField(verbose_name='开始时间')),
                ('e_edate', models.DateField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('p_sdate', models.DateField(verbose_name='开始时间')),
                ('p_edate', models.DateField(verbose_name='结束时间')),
                ('p_content', models.TextField(verbose_name='项目简介')),
            ],
            options={
                'verbose_name': '项目经验',
                'verbose_name_plural': '项目经验',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('blog', models.CharField(max_length=200, verbose_name='博客')),
                ('website', models.CharField(max_length=200, verbose_name='网站')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100, verbose_name='技能')),
                ('s_grade', models.CharField(max_length=3, verbose_name='技能点')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Resume', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Resume', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='education',
            name='e_id',
            field=models.ManyToManyField(to='api.Resume', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Resume', verbose_name='作者'),
        ),
    ]
