# Generated by Django 2.1.3 on 2019-11-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_cover',
            field=models.ImageField(default='null', upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_grade',
            field=models.IntegerField(verbose_name='技能点'),
        ),
    ]
