# Generated by Django 2.1.3 on 2019-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191117_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
    ]
