# Generated by Django 2.1.3 on 2019-11-24 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191122_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('j_sdate', models.DateField(verbose_name='开始时间')),
                ('j_edate', models.DateField(verbose_name='结束时间')),
                ('j_content', models.TextField(verbose_name='工作简介')),
                ('j_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Resume', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
    ]
