# Generated by Django 2.1.3 on 2019-11-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191117_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='education',
            name='e_major',
            field=models.CharField(max_length=50, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='education',
            name='e_name',
            field=models.CharField(max_length=50, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='p_name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='blog',
            field=models.CharField(max_length=200, verbose_name='博客'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='website',
            field=models.CharField(max_length=200, verbose_name='网站'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=100, verbose_name='技能'),
        ),
    ]
