# Generated by Django 2.1.3 on 2019-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_id', models.CharField(max_length=100)),
                ('material_pic', models.FileField(upload_to='')),
                ('material_text', models.CharField(max_length=250)),
                ('material_stime', models.DateTimeField()),
                ('material_etime', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField()),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
    ]
