# Generated by Django 2.1.3 on 2019-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(db_column='nickname', max_length=100, verbose_name='昵称')),
                ('headImg', models.CharField(db_column='headImg', max_length=200, null=True, verbose_name='头像')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name='邮箱')),
                ('age', models.IntegerField(db_column='age', verbose_name='年龄')),
                ('birthyear', models.IntegerField(db_column='birthyear', verbose_name='出生年')),
                ('birthmon', models.IntegerField(db_column='birthmon', verbose_name='出生月')),
                ('birthday', models.IntegerField(db_column='birthday', verbose_name='出生日')),
                ('adress', models.CharField(db_column='adress', max_length=250, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uaername', models.CharField(db_column='username', max_length=100, null=True, verbose_name='账号')),
                ('accountNo', models.IntegerField(db_column='accountNo', verbose_name='户头号')),
                ('password', models.CharField(db_column='password', max_length=100, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
