# Generated by Django 2.1.7 on 2019-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uaername', models.CharField(db_column='username', max_length=100, null=True, verbose_name='账号')),
                ('accountNo', models.IntegerField(default=0)),
                ('password', models.CharField(db_column='password', max_length=100, null=True, verbose_name='密码')),
                ('headImg', models.CharField(db_column='headImg', max_length=200, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
